#!/bin/bash
#
echo ""
echo "-----------------------------------------------------"
echo "SYSTEM MESSAGE: Please Copy Your Information"
echo "-----------------------------------------------------"
echo ""
cat /opt/appdata/plexguide/vpn.info
echo ""
echo "Config Info: Visit http://pgvpn.pgblitz.com or WIKI"
