#!/bin/bash
#
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS ######################################################################
    - cron:
        name: Build a Cron Job - Auto Prune
        special_time: 'hourly'
        job: 'prune 1>/dev/null 2>&1'
        state: present
      ignore_errors: yes
